[metrics] - increment 5
dip96/metrics pull request #5
Opened 2024-02-11 15:53 UTC by dip96

2024-02-14 20:01 UTC, popoffvg requested changes

2024-02-14 20:01 UTC, popoffvg commented on cmd/agent/flags.go
> +var flagRunAddr string
Лучше не использовать глобальные переменные, а для конфигурации сделать отедльный тип.

2024-02-14 20:01 UTC, popoffvg commented on cmd/agent/main.go
> +// TODO переделать ассоциативный масссив на  map[string]interface{}???
Если ты имел ввиду про важно в 3-ем инкременте, то приди, пожалуйста, на 1-1, постараюсь уложиться в полчаса. 
Использовать пустой interface{} нужно только в особых случаях. В курсе это может понадобиться только на последних инкрементах.

2024-02-14 20:01 UTC, popoffvg commented on cmd/agent/main.go
> +	//err := e.Start(flagRunAddr)
Найти пример можно тут: https://echo.labstack.com/docs/start-server

2024-02-14 20:01 UTC, popoffvg commented on cmd/agent/main.go
> +	//не понимаю, как отправить запрос используя echo, не поднимая сервер
echo - это роутер http запросов со стороны сервера. echo не рассчитан на отправку запроса

2024-02-14 20:01 UTC, popoffvg commented on cmd/agent/main.go
> +				return
С ошибкой нужно что-то сделать. Или прекратить обработку и вернуть ошибку, коду, который вызвал sendMetrics. Либо заллогировать. Пропускать не стоит

2024-02-14 20:01 UTC, popoffvg commented on cmd/agent/main.go
> +			errClose := post.Body.Close()
тут не стоит ошибку именовать по-другому. 
В go стандартная практика:
```go
err := do1
if err != nil {return err}

err = do2 // обарти внимание на отсутствие :
if err != nil {return err}

err = do3
if err != nil {return err}
```

2024-02-14 20:01 UTC, popoffvg commented on cmd/server/main.go
> +type Storage interface {
Я забегу вперед и подскажу достаточно расширяемый дизайн для этого задания:
```go
type MetricType string
const(
    MetricTypeGauge MetricType = "gauge"
    MetricTypeCounter MetricType = "counter"
)

type Metric struct{
     Type MetricType
      CounterValue *int
      GaugeValue *float64
}

type Storage interface {
       Get(context.Context, MetricType) (Metric, error)
 	Set(context.Context, Metric) error
 	GetAll(context.Context) ([]metric, error)
 }
```

2024-02-14 20:01 UTC, popoffvg commented on cmd/server/main.go
> +var storage Storage
Не стоит использовать глобальные переменные

2024-02-14 20:01 UTC, popoffvg commented on cmd/server/main.go
> +	switch m := metric.(type) {
Нужно стараться писать максимально типизированный код.
Но очень круто, что не побоялся поработать с рефлексией

2024-02-15 15:14 UTC, dip96 commented on cmd/agent/flags.go
> +var flagRunAddr string
Вынес в отдельный тип. Но всё равно использую глобальную переменную - var conf Config, для получения нужных данных. Чтобы избавиться и от неё, у меня пока только одно решение, это возвращать инициализированный в методе parseFlags "conf := Config{}"  объект

2024-02-15 15:16 UTC, dip96 commented on cmd/agent/main.go
> +// TODO переделать ассоциативный масссив на  map[string]interface{}???
Записался на 19 февраля

2024-02-15 15:21 UTC, dip96 commented on cmd/agent/main.go
> +	//не понимаю, как отправить запрос используя echo, не поднимая сервер
То есть нужно использовать другой роутер/фреймворк для отправки данных?

2024-02-15 15:23 UTC, dip96 commented on cmd/agent/main.go
> +	//err := e.Start(flagRunAddr)
То есть нужно использовать другой роутер/фреймворк для отправки данных?

2024-02-15 15:35 UTC, dip96 commented on cmd/agent/main.go
> +				return
Добавил логирование

2024-02-15 15:35 UTC, dip96 commented on cmd/agent/main.go
> +			errClose := post.Body.Close()
Поправил

2024-02-18 10:08 UTC, dip96 commented on cmd/server/main.go
> +type Storage interface {
Подскажите, а что должен хранить в себе context?

2024-02-18 16:42 UTC, dip96 commented on cmd/server/main.go
> +var storage Storage
Подскажите, а как правильно действовать в таком случаи?

2024-02-18 16:43 UTC, dip96 commented on cmd/server/main.go
> +	switch m := metric.(type) {
Страха не было, потому что на тот момент до конца не понимал, что такое рефлексия. Поправил

2024-02-21 17:14 UTC, popoffvg commented on cmd/agent/main.go
> +	//не понимаю, как отправить запрос используя echo, не поднимая сервер
Нужно использовать стандартную бибилотеку

2024-02-21 18:03 UTC, popoffvg commented on cmd/server/main.go
> +type Storage interface {
Нужно дополнительно посмотреть:
type MetricType string
type MetricType = string

2024-02-21 18:05 UTC, merged